export const BIO_EXPAND = 'BIO_EXPAND'
export const NAVPHONE_EXPAND = 'NAVPHONE_EXPAND'
export const SIDEBAR_EXPAND = 'SIDEBAR_EXPAND'
export const EXPANDS_CLOSE = 'EXPANDS_CLOSE'
export const OVERLAY = "OVERLAY"
